CLIENT_ID = b'CLIENT'
SERVICE_ID = b'SERVICE'

READY_ID = b'READY'
CONFIGURATION_ID = b'CONFIGURATION'
HEARTBEAT_ID = b'HEARTBEAT'
REQUEST_ID = b'REQUEST'
REPLY_ID = b'REPLY'
ERROR_ID = b'ERROR'

# Needs to miss `liveness` heartbeats to be considered dead.
HEARTBEAT_LIVENESS = 5
HEARTBEAT_INTERVAL = 1 # sec
