# conda env create --file environment.yml
# conda env update --file environment.yml --prune
# or, if you're not wanting to use the default env name:
# conda env create --name <myEnvName> --file environment.yml
# conda env update --name <myEnvName--file environment.yml --prune

name: catkit2
dependencies:
  - python=3.7.6
  - numpy
  - scipy
  - matplotlib
  - pyzmq
  - conda-forge::pyvisa>=1.10
  - conda-forge::pyvisa-py
  - pyserial
  - pysnmp
  - requests
  - ftd2xx
  - asdf
  - psutil
  - protobuf
  - conda-forge:hcipy
  - docopt
