# conda env create --file environment.yml
# conda env update --file environment.yml --prune
# or, if you're not wanting to use the default env name:
# conda env create --name <myEnvName> --file environment.yml
# conda env update --name <myEnvName--file environment.yml --prune

name: catkit2
dependencies:
  - python=3.7.6
  - numpy
  - scipy
  - matplotlib
  - pyzmq
  - zeromq>=4.0.0
  - conda-forge::pyvisa>=1.10
  - conda-forge::pyvisa-py
  - conda-forge::nidaqmx-python
  - pyserial
  - pysnmp
  - requests
  - ftd2xx
  - conda-forge::asdf
  - pyyaml
  - psutil
  - protobuf
  - libprotobuf
  - conda-forge:hcipy
  - docopt
  - pip
  - cmake>=3.0.0
  - conda-forge::doxygen
  - sphinx
  - conda-forge::sphinx-automodapi
  - conda-forge::breathe==4.32.0
  - conda-forge::sphinx_rtd_theme
  - networkx
  - pytest
  - flake8
  - pip:
    - zwoasi>=0.0.21 # Requires additional manual install of driver(s) from https://astronomy-imaging-camera.com/software-drivers
