[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
build.verbose = true
logging.level = "INFO"

[project]
name = "catkit2"
version = "0.0.1"
authors = [
  {name = "E.H. Por et al."},
]
description = "A library for controlling testbed hardware"
requires-python = ">=3.7"
dependencies = [
]
maintainers = [
  {name = "Emiel Por", email = "epor@ucsc.edu"},
  {name = "Remi Soummer", email = "soummer@stsci.edu"},
  {name = "Iva Laginja", email = "iva.laginja@obspm.fr"}
]
readme = "README.md"
license = {file = "LICENSE.rst"}
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://spacetelescope.github.com/catkit2"
Documentation = "https://spacetelescope.github.io/catkit2"
Repository = "https://spacetelescope.github.com/catkit2.git"

[project.entry-points."catkit2.services"]
aimtti_plp_device = "catkit2.services.aimtti_plp_device.aimtti_plp_device"
aimtti_plp_device_sim = "catkit2.services.aimtti_plp_device_sim.aimtti_plp_device_sim"
allied_vision_camera = "catkit2.services.allied_vision_camera.allied_vision_camera"
bmc_deformable_mirror_hardware = "catkit2.services.bmc_deformable_mirror_hardware.bmc_deformable_mirror_hardware"
bmc_deformable_mirror_sim = "catkit2.services.bmc_deformable_mirror_sim.bmc_deformable_mirror_sim"
camera_sim = "catkit2.services.camera_sim.camera_sim"
dummy_camera = "catkit2.services.dummy_camera.dummy_camera"
empty_service = "catkit2.services.empty_service.empty_service"
flir_camera = "catkit2.services.flir_camera.flir_camera"
hamamatsu_camera = "catkit2.services.hamamatsu_camera.hamamatsu_camera"
newport_picomotor = "catkit2.services.newport_picomotor.newport_picomotor"
newport_picomotor_sim = "catkit2.services.newport_picomotor_sim.newport_picomotor_sim"
newport_xps_q8 = "catkit2.services.newport_xps_q8.newport_xps_q8"
newport_xps_q8_sim = "catkit2.services.newport_xps_q8_sim.newport_xps_q8_sim"
ni_daq = "catkit2.services.ni_daq.ni_daq"
ni_daq_sim = "catkit2.services.ni_daq_sim.ni_daq_sim"
nkt_superk = "catkit2.services.nkt_superk.nkt_superk"
nkt_superk_sim = "catkit2.services.nkt_superk_sim.nkt_superk_sim"
oceanoptics_spectrometer = "catkit2.services.oceanoptics_spectrometer.oceanoptics_spectrometer"
oceanoptics_spectrometer_sim = "catkit2.services.oceanoptics_spectrometer_sim.oceanoptics_spectrometer_sim"
omega_ithx_w3 = "catkit2.services.omega_ithx_w3.omega_ithx_w3"
omega_ithx_w3_sim = "catkit2.services.omega_ithx_w3_sim.omega_ithx_w3_sim"
safety_manual_check = "catkit2.services.safety_manual_check.safety_manual_check"
safety_monitor = "catkit2.services.safety_monitor.safety_monitor"
simple_simulator = "catkit2.services.simple_simulator.simple_simulator"
snmp_ups = "catkit2.services.snmp_ups.snmp_ups"
snmp_ups_sim = "catkit2.services.snmp_ups_sim.snmp_ups_sim"
thorlabs_cld101x = "catkit2.services.thorlabs_cld101x.thorlabs_cld101x"
thorlabs_cld101x_sim = "catkit2.services.thorlabs_cld101x_sim.thorlabs_cld101x_sim"
thorlabs_cube_motor_kinesis = "catkit2.services.thorlabs_cube_motor_kinesis.thorlabs_cube_motor_kinesis"
thorlabs_cube_motor_kinesis_sim = "catkit2.services.thorlabs_cube_motor_kinesis_sim.thorlabs_cube_motor_kinesis_sim"
thorlabs_fw102c = "catkit2.services.thorlabs_fw102c.thorlabs_fw102c"
thorlabs_mcls1 = "catkit2.services.thorlabs_mcls1.thorlabs_mcls1"
thorlabs_mcls1_sim = "catkit2.services.thorlabs_mcls1_sim.thorlabs_mcls1_sim"
thorlabs_mff101 = "catkit2.services.thorlabs_mff101.thorlabs_mff101"
thorlabs_mff101_sim = "catkit2.services.thorlabs_mff101_sim.thorlabs_mff101_sim"
thorlabs_pm = "catkit2.services.thorlabs_pm.thorlabs_pm"
thorlabs_pm_sim = "catkit2.services.thorlabs_pm_sim.thorlabs_pm_sim"
thorlabs_tsp01 = "catkit2.services.thorlabs_tsp01.thorlabs_tsp01"
thorlabs_tsp01_sim = "catkit2.services.thorlabs_tsp01_sim.thorlabs_tsp01_sim"
web_power_switch = "catkit2.services.web_power_switch.web_power_switch"
web_power_switch_sim = "catkit2.services.web_power_switch_sim.web_power_switch_sim"
zwo_camera = "catkit2.services.zwo_camera.zwo_camera"

[project.entry-points."catkit2.proxies"]
camera = "catkit2.testbed.proxies.camera:CameraProxy"
deformable_mirror = "catkit2.testbed.proxies.deformable_mirror:DeformableMirrorProxy"
flip_mount = "catkit2.testbed.proxies.flip_mount:FlipMountProxy"
newport_picomotor = "catkit2.testbed.proxies.newport_picomotor:NewportPicomotorProxy"
newport_xps_q8 = "catkit2.testbed.proxies.newport_xps:NewportXpsQ8Proxy"
ni_daq = "catkit2.testbed.proxies.ni_daq:NiDaqProxy"
nkt_superk = "catkit2.testbed.proxies.nkt_superk:NktSuperkProxy"
oceanoptics_spectrometer = "catkit2.testbed.proxies.oceanoptics_spectrometer:OceanopticsSpectroProxy"
thorlabs_cube_motor_kinesis = "catkit2.testbed.proxies.thorlabs_cube_motor_kinesis:ThorlabsCubeMotorKinesisProxy"
thorlabs_mcls1 = "catkit2.testbed.proxies.thorlabs_mcls1:ThorlabsMcls1"
web_power_switch = "catkit2.testbed.proxies.web_power_switch:WebPowerSwitchProxy"

[project.scripts]
mtop = "catkit2.tui.mtop:main"
