CLIENT_ID = b'CLIENT'
SERVICE_ID = b'SERVICE'

REGISTER_ID = b'REGISTER'
OPENED_ID = b'OPENED'
CONFIGURATION_ID = b'CONFIGURATION'
HEARTBEAT_ID = b'HEARTBEAT'
REQUEST_ID = b'REQUEST'
REPLY_ID = b'REPLY'

# Needs to miss `liveness` heartbeats to be considered dead.
HEARTBEAT_LIVENESS = 5
HEARTBEAT_INTERVAL = 1 # sec
