testbed_server:
  port: 8080
  safety:
    service_name: safety
    check_interval: 60
    safe_interval: 180

services:
  lopr_camera:
    service_type: flir_camera
    simulated_module_type: sim_camera
    interface: camera

    serial_number: 21081906
    width: 128
    height: 128
    offset_x: 112
    offset_y: 244
    adc_bit_depth: 12bit
    pixel_format: mono12p

  science_camera:
    service_type: zwo_camera
    simulated_module_type: sim_camera

    device_name: ZWO ASI178MM(3)
    subarray_x: 2614
    subarray_y: 422
    width: 712
    height: 712

  ta_camera:
    service_type: zwo_camera
    simulated_module_type: sim_camera

    device_name: ZWO ASI290MM(1)
    subarray_x: 710
    subarray_y: 643
    width: 464
    height: 464

  zernike_camera:
    service_type: zwo_camera
    simulated_module_type: sim_camera

    device_name: ZWO ASI178MM(2)
    subarray_x: 1808
    subarray_y: 993
    width: 1024
    height: 1024

  pupil_camera:
    service_type: zwo_camera
    simulated_module_type: sim_camera

    device_name: ZWO ASI178MM(4)

  boston_dm:
    service_type: bmc_dm

    serial_number: 25CW018#008
    command_length: 2048

    channels:
      - correction_howfs
      - probe
      - correction_lowfs
      - aberration
      - atmosphere
      - poke
      - astrogrid

  iris_dm:
    service_type: irisao_dm

    mirror_serial: PWA37-05-04-0705
    driver_serial: 13130030
    usb_power_strip_id: web_power_switch_1
    usb_hub_outlet_id: iris_usb_hub

    channels:
      - correction
      - aberration

  newport_xps:
    service_type: newport_xps_q8
    interface: newport_xps_q8

    ip_address: 192.168.192.117
    port: 5001
    timeout: 20
    update_interval: 1
    atol: 0.001
    motors:
      FPM_X:
        nominal: coron
        in_beam: 10.296
        out_of_beam: 9
      Lyot_Y:
        nominal: in_beam
        in_beam: 2.712
        out_of_beam: 50 # WARNING: do not modify this, it could hit the FPM.
      Lyot_X:
        nominal: 9.788
      Lyot_Z:
        nominal: 10.6
      Img_Camera:
        nominal: 13.67
      PR_Camera:
        nominal: -8.69
      Zernike_X:
        nominal: in_beam
        in_beam: 5.777
        out_of_beam: 5

  apodizer_mount:
    service_type: newport_picomotor

    ip_address: 192.168.192.151
    max_step: 2147483647
    timeout: 60
    daisy: 0
    axes:
      x: 1
      y: 2
    sleep_per_step: 0.0005
    sleep_base: 0.1

  quad_cell_mount:
    service_type: newport_picomotor

    ip_address: 192.168.192.151
    max_step: 2147483647
    timeout: 60
    axes:
      x: 3
      y: 4
    daisy: 0
    sleep_per_step: 0.0005
    sleep_base: 0.1

  zwfs_mount:
    service_type: newport_picomotor

    ip_address: 192.168.192.152
    max_step: 2147483647
    timeout: 60
    daisy: 0
    axes:
      x: 4
      y: 1
    sleep_per_step: 0.0005
    sleep_base: 0.1

  beam_dump:
    service_type: thorlabs_mff101

    serial_number: 37000085
    in_beam: 1
    out_of_beam: 2

  phase_retrieval_mirror:
    service_type: thorlabs_mff101

    serial_number: 37001725
    in_beam: 1
    out_of_beam: 2

  fpm_illuminator:
    service_type: thorlabs_mff101

    serial_number: 37871220
    in_beam: 2
    out_of_beam: 1

  pupil_illuminator:
    service_type: thorlabs_mff101

    serial_number: 37002369
    in_beam: 2
    out_of_beam: 1

  tsp01_1:
    service_type: thorlabs_tsp01

    serial_number: M00542273

  tsp01_2:
    service_type: thorlabs_tsp01

    serial_number: M00685167

  tsp01_3:
    service_type: thorlabs_tsp01

    serial_number: M001546345

  omega_dm1:
    service_type: omega_ithx_w3

    ip_address: 192.168.192.132
    time_interval: 30

  omega_dm2:
    service_type: omega_ithx_w3

    ip_address: 192.168.192.32
    time_interval: 30

  blue_ups:
    service_type: snmp_ups

    ip_address: 10.128.242.6
    port: 161
    snmp_oid: 1.3.6.1.4.1.534.1.3.5.0
    community: palapa
    pass_status: 3

  lab_ups:
    service_type: snmp_ups

    ip_address: 192.168.192.20
    port: 161
    snmp_oid: .1.3.6.1.4.1.318.1.1.1.4.1.1.0
    community: public
    pass_status: 2

  web_power_switch_1:
    service_type: web_power_switch

    user: admin
    password: hicat
    ip_address: 192.168.192.11
    dns: webpowerswitch

    # Plugged-in devices with their outlet number:
    outlets:
      npoint_tiptilt_lc_400: 1
      iris_usb_hub: 2
      newport_xps_q8: 3
      iris_dm: 4
      quad_cell: 5
      air_valve: 6
      pupil_led: 7
      fpm_led: 8

  color_filter_wheel:
    service_type: thorlabs_fw102c

    visa_id: ASRL4::INSTR

    filters:
      610nm: 1
      620nm: 2
      640nm: 3
      660nm: 4
      670nm: 5
      broadband: 6

  nd_filter_wheel:
    service_type: thorlabs_fw102c

    visa_id: ASRL6::INSTR

    filters:
      clear: 1
      2.8_percent: 2
      12_percent: 3
      9_percent: 4

  safety:
    service_type: safety_monitor

    check_interval: 60

    safeties:
      - humidity_dm1:
          module_name: omega_dm1
          stream_name: humidity
          minimum_value: 1
          maximum_value: 28
          safe_interval: 60
      - humidity_dm2:
          module_name: omega_dm2
          stream_name: humidity
          minimum_value: 1
          maximum_value: 28
          safe_interval: 60
      - temperature_dm1:
          module_name: omega_dm1
          stream_name: temperature
          minimum_value: 0
          maximum_value: 29
          safe_interval: 60
      - temperature_dm2:
          module_name: omega_dm2
          stream_name: temperature
          minimum_value: 0
          maximum_value: 29
          safe_interval: 60
      - lab_ups:
          module_name: lab_ups
          stream_name: power_ok
          minimum_value: 0.5
          maximum_value: 1.5
          safe_interval: 60
      - blue_ups:
          module_name: blue_ups
          stream_name: power_ok
          minimum_value: 0.5
          maximum_value: 1.5
          safe_interval: 60

  a:
    service_type: test_module_python

  b:
    service_type: test_module_cpp

  environment_viewer:
    service_type: environment_viewer

  example_camera:
    service_type: dummy_camera
    interface: camera

    exposure_time: 1000
    gain: 0
    width: 256
    height: 256
    offset_x: 0
    offset_y: 0
    flux: 100000000
    sensor_width: 256
    sensor_height: 256

  camera_viewer:
    service_type: camera_gui

    camera_name: example_camera
