# -*- coding: utf-8 -*-
"""
Created on Thu Oct 10 16:56:37 2024

@author: lameier - using original code by Hari who worked with Phasics
"""
import PySID4x as sid
import numpy as np
from catkit2.testbed.service import Service
import threading

class IllegalArgumentError(ValueError):
    pass

class PhasicsCam(Service):
    """
    A service class for the Phasics camera.

    A camera service with functionality for taking measurements,
    starting and stopping live acquisitions, and managing an image buffer.

    Parameters
    ----------
    Service : catkit2.testbed.service.Service
        The base service class from which this class inherits.
    """
    def __init__(self):
        """
        Initializes the PhasicsCam object.

        Sets up the instrument parameters, including exposure time, image dimensions,
        and frame buffer size. Also initializes data streams and registers commands.

        Attributes
        ----------
        exposure_time : int
            The default exposure time in milliseconds.
        image_height : int
            The height of the images in pixels.
        image_width : int
            The width of the images in pixels.
        num_frames_in_buffer : int
            The number of frames to maintain in the data buffer.
        images : catkit2.testbed.service.DataStream
            A data stream to manage phase map image frames.
        intensity : catkit2.testbed.service.DataStream
            A data stream to manage intensity image frames.
        """
        super().__init__('phasics_cam')
        # in dummy mode fake data is generated by API or device
        SID4Session = self.initialize_sid4_session(mode=self.config.get('mode', 'normal'))
        self.exposure_time = self.config.get('exposure_time', 504)

        self.num_frames_in_buffer = self.config.get('buffer_frames', 32)

        # Load the mask file and initialize the camera
        maskname = self.config.get('mask')
        self.log.info(f'loading mask {maskname}')
        SID4Session.change_mask(filename=maskname)
        SID4Session.Camera.load()
        SID4Session.Camera.set_attribute('Exposure', self.exposure_time)
        SID4Session.modify_user_profile(wavelength=self.config.get('wavelength'))
        SID4Session.Zernike.open()
        poly_order = 9
        SID4Session.Zernike.update_projection(poly_order, source='user profile')

        self.session = SID4Session

        # take an image to determine the size of the frames based on the mask provided
        self.log.info('getting test image')
        self.set_exposure_time(self.exposure_time)
        test_image = self.take_measurement()
        self.log.info(f'test image shape = {test_image.shape}')
        self.image_height = test_image.shape[0]
        self.image_width = test_image.shape[1]

        # Create data streams.
        # in order to re-use the camera interface I must have something called 'images' which will be an alias for the phase map
        self.images = self.make_data_stream('images', 'float32', [self.image_height, self.image_width], self.num_frames_in_buffer)
        self.intensity = self.make_data_stream('intensity', 'float32', [self.image_height, self.image_width], self.num_frames_in_buffer)
        self.is_acquiring = self.make_data_stream('is_acquiring', 'int8', [1], self.num_frames_in_buffer)

        # create commands
        self.make_command('take_measurement', self.take_measurement)
        self.make_command('start_acquisition', self.start_acquisition)
        self.make_command('end_acquisition', self.end_acquisition)
        self.make_command('phase_filtering', self.phase_filtering)
        self.make_command('phase_projection', self.phase_projection)

        self.framecounter = 0
        self.is_acquiring.submit_data(np.array([0], dtype='int8'))
        self.should_be_acquiring = threading.Event()
        self.should_be_acquiring.clear()
        self.log.info('finished initializing phasics cam service')

    def set_exposure_time(self, exposure_time):
        """
        Sets the camera's exposure time in ms

        Parameters
        ----------
        exposure_time : int
            The exposure time in milliseconds.

        Returns
        -------
        bool
            True if the exposure time is successfully set.
        """
        self.session.Camera.set_attribute('Exposure', exposure_time)
        self.exposure_time = exposure_time
        return True

    def initialize_sid4_session(self, mode='normal'):
        """
        Import DLL and create SID4 Session.

        Returns
        -------
        PySID4x.Session
            The sid4 Session
        """
        return sid.Session(self.config.get('dll_path'), self.config.get('usr_profile_path'), mode=mode)

    def take_measurement(self, num_images=1):
        """
        Parameters
        ----------
        num_images : int, optional
            The number of exposures to average. The default is 1.

        Returns
        -------
        numpy.ndarray
            The phase map (single or averaged) of dimensions (image_height, image_width).
        """
        session_name = self.session
        session_name.Camera.start_live_mode()

        if num_images > 1:
            for i in range(num_images):
                if i == 0:
                    phase_cube, intensity_cube, _ = session_name.Analysis.grab_live_mode()
                else:
                    phase_map_temp, intensity_temp, _ = session_name.Analysis.grab_live_mode()
                    phase_cube = np.dstack((phase_cube, phase_map_temp))
                    intensity_cube = np.dstack((intensity_cube, intensity_temp))
            phase_map = np.mean(phase_cube, axis=2)
            intensity = np.mean(intensity_cube, axis=2)
        else:
            phase_map, intensity, _ = session_name.Analysis.grab_live_mode()
        session_name.Camera.stop_live_mode()

        return phase_map

    def phase_projection(self, phase=None):
        """
        Parameters
        ----------
        phase : numpy.ndarray, optional
            The phase map (single or averaged) of dimensions (image_height, image_width).
        Returns
        -------
        1D numpy array
            The zernike phase projection coefficients
        """
        if phase is None:
            phase = self.take_measurement()
        return self.session.Zernike.phase_projection(phase)

    def phase_filtering(self, phase=None, projection_coefficient=None, index_list=None, residual=None):
        """
        Parameters
        ----------
        phase : numpy.ndarray
            The phase map (single or averaged) of dimensions (image_height, image_width).
        phase_projection_coefficient :  (1D numpy array)
            Zernike projection coefficient
        index_list : (1D numpy array)
            List of the projection coefficient index to filter
        residual : bool
            If True the residual is return, if False the filtered phase is returned

        Returns
        -------
        numpy.ndarray
            2D Filtered phase map.
        """
        if phase is None:
            raise IllegalArgumentError('phase srequired arg1')

        if projection_coefficient is None:
            raise IllegalArgumentError('projection_coefficient required arg2')

        if index_list is None:
            raise IllegalArgumentError('index_list required arg3')

        if residual is None:
            raise IllegalArgumentError('residual required arg4')

        return self.session.Zernike.phase_filtering(phase, projection_coefficient, index_list, residual)

    def snap(self, num_images=1):
        """
        Parameters
        ----------
        num_images : int, optional
            The number of exposures to average. The default is 1.

        Returns
        -------
        list
            A list consisting of the interferograms.
        """
        sess = self.session
        cam = sess.Camera
        SDK = sid.SDK
        # LM - The only way that seems to properly start the grabs is the live mode
        sess.Camera.start_live_mode()
        interferograms = list()
        for i in range(num_images):
            # low level grab function from SDK
            interferograms.append(SDK.grab(cam))
        sess.Camera.stop_live_mode()
        return interferograms

    def close(self):
        """
        Closes the Camera session.
        """
        self.session.Camera.close()
        self.session.close()

    def main(self):
        """
        Main loop to manage data acquisition and processing.
        """
        while not self.should_shut_down:
            if self.should_be_acquiring.wait(0.05):
                self.acquisition_loop()

    def acquisition_loop(self):
        """
        Handle continuous data acquisition while the service is running.
        """
        try:
            self.is_acquiring.submit_data(np.array([1], dtype='int8'))
            session_name = self.session
            session_name.Camera.start_live_mode()

            while self.should_be_acquiring.is_set() and not self.should_shut_down:
                phase_map, intensity, _ = session_name.Analysis.grab_live_mode()
                has_correct_parameters = np.allclose(self.images.shape, phase_map.shape)

                if not has_correct_parameters:
                    self.images.update_parameters('float32', phase_map.shape, self.num_frames_in_buffer)
                self.images.submit_data(phase_map.astype('float32'))

                has_correct_parameters = np.allclose(self.intensity.shape, intensity.shape)

                if not has_correct_parameters:
                    self.intensity.update_parameters('float32', intensity.shape, self.num_frames_in_buffer)
                self.intensity.submit_data(intensity.astype('float32'))
        finally:
            session_name.Camera.stop_live_mode()
            self.is_acquiring.submit_data(np.array([0], dtype='int8'))


    def start_acquisition(self):
        """
        Start the data acquisition process.
        """
        self.should_be_acquiring.set()
        self.is_acquiring.submit_data(np.array([1], dtype='int8'))


    def end_acquisition(self):
        """
        End the data acquisition process.
        """
        self.should_be_acquiring.clear()
        self.is_acquiring.submit_data(np.array([0], dtype='int8'))

if __name__ == '__main__':
    service = PhasicsCam()
    service.run()
