name: Linting

on:
  workflow_dispatch:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
    - develop

jobs:
  linter:
    name: Flake8
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7.6]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install flake8
      shell: bash
    - name: Lint with flake8
      run: flake8 . --max-line-length=127 --count --statistics
      shell: bash
