name: Linting

on:
  workflow_dispatch:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
    - develop

jobs:
  linter:
    name: Flake8
    runs-on: ubuntu-20.04
    env:
      EXCLUDE_DIRS: "NKTP_DLL.py"

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.6'
    - name: Install flake8
      run: |
        python -m pip install flake8
      shell: bash
    - name: Lint with flake8
      run: flake8 . --max-line-length=127 --count --statistics
      shell: bash
