name: Testing

on:
  workflow_dispatch:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
    - develop

jobs:
  pytest:
    name: Pytest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          auto-activate-base: false
    - name: Install dependencies
      run: |
        cd extern/
        bash ./download.sh
        cd ../
        conda env create --name ci-env --file environment.yml
        conda activate ci-env
        python setup.py develop
      shell: bash -l {0}
    - name: Run tests
      run: |
        conda activate ci-env
        pytest
      shell: bash -l {0}
