name: Testing

on:
  workflow_dispatch:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
    - develop

jobs:
  pytest:
    name: Pytest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
          miniconda-version: "latest"
          auto-update-conda: true
          auto-activate-base: false
    - name: Switch to gcc-10 on linux
      if: runner.os == 'Linux'
      run: |
        sudo apt install gcc-10 g++-10 cpp-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
    - name: Install dependencies
      run: |
        cd extern/
        bash ./download.sh
        cd ../
        conda env create --name ci-env --file environment.yml
      shell: bash -l {0}
    - name: Print debugging information
      run: |
        conda activate ci-env
        conda list
      shell: bash -l {0}
    - name: Install catkit2
      run: |
        conda activate ci-env
        python setup.py develop
      shell: bash -l {0}
    - name: Run tests
      run: |
        conda activate ci-env
        pytest
      shell: bash -l {0}
